### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#110]
I must have break the build but I can't reproduce this issue on my machine: https://travis-ci.org/asciidoctor/asciidoctor.js

```
NameError: uninitialized constant Opal::Tilt
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets/processor.rb:21:in `<module:Opal>'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets/processor.rb:7:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets/environment.rb:2:in `require'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets/environment.rb:2:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets.rb:1:in `require'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal/sprockets.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal.rb:4:in `require'
/home/travis/.rvm/gems/ruby-1.9.3-p194/gems/opal-0.6.3/lib/opal.rb:4:in `<top (required)>'
/home/travis/build/asciidoctor/asciidoctor.js/Rakefile:1:in `require'
/home/travis/build/asciidoctor/asciidoctor.js/Rakefile:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
 Use --force to continue.
```

@mojavelinux Any idea why Opal is complaining ?

**Comment by anthonny** [comment]
I found this code in the opal code source : 
https://github.com/opal/opal/blob/570dfb1286f0c91d536ab24b54556198eff36be6/opal.gemspec#L22

It seems that the version is not specify

Is it possible that now Opal point on sprockets v3.0.1  ? I can't found the Tilt definition https://github.com/rails/sprockets/search?utf8=%E2%9C%93&q=Tilt

Maybe i'm totally wrong :smile:

**Comment by Mogztter** [comment]
I think you may be right, thanks. I will dig a little bit deeper :smile:
