### ISSUE TITLE
Pointers on writing Antora extensions

### ISSUE THREAD

**Issue by maxime-michel** [asciidoctor/asciidoctor.js#1236]
Thanks to the example I found [here](https://pagure.io/fedora-docs/docs-fp-o/pull-request/93.patch), I was able to get an inline macro to work.

I would like to write a preprocessor now, but I'm unable to sort out the syntax that would be required. I would much rather adapt my macro to the syntax I have seen in #555. With such API, it would be easier for me to find my way.

However, I can't get that to work. The minute I `require('asciidoc')()`, things blow up:

    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)
        at Object.Opal.allocate_class (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:450:7)
        at Opal.klass (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:518:18)
        at /Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:4919:16
        at Opal.modules.corelib/error (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:5072:5)
        at Object.Opal.load (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:7)
        at constructor.Opal.require (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:2339:17)
        at Opal.modules.opal/base (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:5439:8)
        at Object.Opal.load (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:7)
        at constructor.Opal.require (/Users/maxime/Documents/antora-site/node_modules/asciidoctor-opal-runtime/src/opal.js:2339:17)

I intend to publicly document the inline macro I've been able to get to work, so that somebody else can benefit from the rather painful research. If you could give me a couple of pointers on what's required in order to make the nicer syntax work, then that'd benefit everybody. Thanks!

**Comment by mojavelinux** [comment]
You can find several more examples here: https://github.com/couchbase/docs-site/tree/master/lib

I strongly recommend avoiding the preprocessor though. It's okay as a lifecycle hook. But if a preprocessor modifies the lines, it can have unintended consequences unless you really know what you are doing (and even I don't always remember what has to be done). It's much safer to use any of the other extension points for manipulating the content.

**Comment by maxime-michel** [comment]
Thanks a lot for unblocking us this quickly!

The reason I thought of a preprocessor is to dynamically add a page attribute based on a REST request. I'll see how else this could be done now that I've got working examples to play with.

**Comment by mojavelinux** [comment]
> The reason I thought of a preprocessor is to dynamically add a page attribute based on a REST request.

I'm pretty sure that's one of the valid use cases for a preprocessor without side effects. You can set the attribute on the document object or even push a line onto the front of the reader. It's when you read the lines that you get into trouble (because it doesn't end up parsing the document like it normally does).

**Comment by mojavelinux** [comment]
For example, this extension (although written in Ruby) doesn't read any lines, but it does add new attributes: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/git-metadata-preprocessor/extension.rb

**Comment by maxime-michel** [comment]
> I intend to publicly document the inline macro I've been able to get to work, so that somebody else can benefit from the rather painful research.

A couple months later, here it is: https://www.magnolia-cms.com/blog/tips-for-writing-antora-macros.html. Hope it helps!
