### ISSUE TITLE
Potential incompatibility with esbuild, not working in projects built with vite + vue3

### ISSUE THREAD

**Issue by JackySu** [asciidoctor/asciidoctor.js#1685]
It appears that this module will run into errors when I put it in a project built with vite + vue3 + js only
```
Uncaught TypeError: Cannot assign to read only property 'length' of function 'function() {
          var block2 = alias.$$p, args2, i, ii;
          args2 = new Array(arguments.length);
   ...<omitted>... }'
    at Opal2.alias (asciidoctor.js:1869:11)
    at asciidoctor.js:2809:10
    at Opal.modules.corelib/module (asciidoctor.js:3558:3)
    at Opal2.load (asciidoctor.js:2314:7)
    at Opal2.require (asciidoctor.js:2342:17)
    at Opal.modules.opal/base (asciidoctor.js:5469:8)
    at Opal2.load (asciidoctor.js:2314:7)
    at Opal2.require (asciidoctor.js:2342:17)
    at asciidoctor.js:20069:8
    at node_modules/@asciidoctor/core/dist/browser/asciidoctor.js (asciidoctor.js:20079:1)
```
but works fine without any issue in projects built with vue-cli + vue3 + js
maybe there are potential incompatibility issues against esbuild?

**Comment by ggrossetie** [comment]
That's a duplicate of https://github.com/asciidoctor/asciidoctor.js/issues/686
The version of Opal used by Asciidoctor 2.x does not support strict mode hence the error.

Could you please try with https://github.com/asciidoctor/asciidoctor.js/releases/tag/v3.0.0-alpha.4 ?

**Comment by JackySu** [comment]
The error still exist after using the latest build
```runtime-core.esm-bundler.js:40 [Vue warn]: Failed to resolve component: AsciiDocViewer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>```
I'm a newbie at frontend, any suggestions with it? Much appreciated!

**Comment by JackySu** [comment]
Thank you very much! I managed to fix this issue
