### ISSUE TITLE
Windows: error when running npm run examples

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#210]
The following error is thrown when running `npm run examples` on Windows:

```
compile examples
 - compile examples/asciidoctor_example.rb
F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16194
          } else { throw $err; }
                   ^

Exception: An error occurred while compiling: examples/asciidoctor_example
self.working.substring is not a function
    at Opal.defs.TMP_1 [as $new] (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4853:15)
    at ːexception (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4871:31)
    at $Compiler.ːraise (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4612:31)
    at $Compiler.ːcompile (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:14489:27)
    at F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:15877:20
    at $RubyProcessor.ːcompiled (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:15878:29)
    at $RubyProcessor.ːrequires (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:15893:23)
    at $Builder.ːbuild_str (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16183:63)
    at $Builder.ːbuild (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16168:21)
    at OpalCompiler.compile (F:\dev\workspaces\opensource\asciidoctor.js\npm\opal-compiler.js:28:24)
```

Windows 1 SP1 (64bits)

**Comment by Mogztter** [comment]
Try to reproduce this issue on AppVeyor. In other words, AppVeyor should run `npm run examples`
