### ISSUE TITLE
Windows: error when running npm run build

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#211]
The following exception is throws when running `npm run build` on Windows:

```
F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4627
      throw exception;
      ^
MissingRequire: can't find file: "securerandom" in ["C:\\dev\\workspaces\\opensource\\asciidoctor.js\\opal", "C:\\dev\\workspaces\\opensource\\asciidoctor.js\\stdlib", "C:\\dev\\workspaces\\opensource\\asciidoctor.js", "C:\\dev\\workspaces\\opensource\\asciidoctor.js\\node_modules\\opal-compiler\\src\\stdlib", "C:\\dev\\workspaces\\opensource\\asciidoctor.js\\lib", "C:\\dev\\workspaces\\opensource\\asciidoctor.js\\build\\asciidoctor\\lib", "C:\\dev\\workspaces\\opensource\\asciidoctor.js\\extensions-lab\\lib"]
    at Opal.defs.TMP_1 [as $new] (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4853:15)
    at ːexception (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4871:31)
    at $Builder.ːraise (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:4612:31)
    at $Builder.ːread (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16298:108)
    at F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16313:23
    at $Builder.ːprocess_require (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16314:26)
    at $a.$$p.TMP_22 (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16333:23)
    at Opal.yield1 (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:1198:14)
    at Array.ːcollect (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-runtime\src\opal.js:10944:26)
    at $Builder.ːprocess_requires (F:\dev\workspaces\opensource\asciidoctor.js\node_modules\opal-compiler\src\opal-builder.js:16333:106)
```

As a workaround you can add [securerandom.rb](https://github.com/opal/opal/blob/master/stdlib/securerandom.rb) to `node_modules/opal-compiler/src/stdlib/`

**Comment by mojavelinux** [comment]
That's strange because Asciidoctor doesn't use securerandom.

**Comment by Mogztter** [comment]
> That's strange because Asciidoctor doesn't use securerandom.

You are right! I think `extensions-lab` submodule was outdated on my working copy.
I've removed `securerandom` from the chart extension a few months ago: https://github.com/asciidoctor/asciidoctor-extensions-lab/commit/a6c32c05f02f969d3fe9dc119b7ed46a2ba3fcc8#diff-327102a98741c995aef50df2ca656f25

**Comment by mojavelinux** [comment]
:+1:
