### ISSUE TITLE
Different behaviors when compared with Asciidoctor Ruby

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#220]
* Render to RevealJS

If I use this command in a terminal using asciidoctor ruby 1.5.4

```
asciidoctor -T asciidoctor-reveal.js/templates/slim revealjs.adoc
```

then the adoc file will be converted into a RevealJS HTML file and the slides could be visualized in a browser. Remark: reveal.js project has been downloaded and is part of the folder containing the html generated.

If I try to do the same thing using asciidoctor.js, then we get this error 

```
Error: ENOENT: no such file or directory, open 'data/stylesheets/asciidoctor-default.css'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:872:118
    at ːread (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:903:84)
    at ːread (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:915:33)
    at $Stylesheets.ːprimary_stylesheet_data (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:11152:146)
    at $Stylesheets.ːembed_primary_stylesheet (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:11158:36)
    at $Html5Converter.ːdocument (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:4684:44)
    at $Html5Converter.ː__send__ (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/node_modules/opal-runtime/src/opal.js:3228:21)
    at $Html5Converter.ːconvert (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:4167:24)
    at $Document.ːconvert (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:7110:35)
    at module_constructor.ːconvert (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:12411:22)
    at module_constructor.ːconvert_file (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:12473:21)
```

Here are the config used for that conversion

```
{"safe"=>"unsafe", 
 "to_file"=>"slideshow.html",
 "to_dir"=>"/Users/chmoulli/Temp/litoria/t4/generated",
 "attributes"=>{
      "templatedir"=>"/Users/chmoulli/Temp/litoria/t4/_temp/revealjs-backend/templates/jade",
      "nofooter"=>"yes", 
      "icons"=>"font", 
      "source-highlighter"=>"highlight.js"
    }
}
```

Conclusion: The logic followed within asciidoctor.js is different from Ruby. Is it the intended behaviour ? Asciidoctor Ruby is able to select Revealjs converter even if the backend type = html5. Is this assumption correct ?

* Same test but using the backend attribute `revealjs`

If I do again the same test but now using as attribute `backend: revealjs`, that will work as Asciidoctor.js will load the RevealjsConverter and not anymore html5Converter but we have another issue as we concatenate the path of the `templatedir` with the keywork `revealjs`

```
Error: ENOENT: no such file or directory, open '/Users/chmoulli/Temp/litoria/t4/_temp/revealjs-backend/templates/jade/revealjs/document.jade'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:872:118
    at ːread (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.js:903:84)
    at ːrender (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-slide.js:21:37)
    at $RevealjsConverter.ːconvert (/Users/chmoulli/MyProjects/litoria/node_modules/asciidoctor.js/dist/npm/asciidoctor-revealjs.js:26:36)
```

Is this approach logic ?

**Comment by Mogztter** [comment]
I think both issues are now fixed in #227 and #219.
@cmoulliard Can I close this issue ?

**Comment by cmoulliard** [comment]
> Can I close this issue ?

Yes

**Comment by Mogztter** [comment]
:+1:
