### ISSUE TITLE
Version 1.5.5-4 breaks gulp-asciidoctor

### ISSUE THREAD

**Issue by lafe** [asciidoctor/asciidoctor.js#268]
The new update of Asciidoctor.js breaks gulp-asciidoctor. When the gulp plugin uses version 1.5.5-4 it crashes, whereas version 1.5.5-3 works. In both cases, the same gulp scripts and gulp-asciidoctor module are used.

Result with Version 1.5.5-3:
``` PowerShell
> gulp watch
[11:40:50] Using gulpfile C:\Code\...\gulpfile.js
...
[11:40:51] Starting 'build-asciidoc'...
[11:40:51] Finished 'build-asciidoc' after 130 ms
...
```

Version 1.5.5-4:
``` PowerShell
> gulp watch
C:\Code\...\node_modules\gulp-asciidoctor\index.js:6
var processor = asciidoctorJs.Asciidoctor(true);
                              ^

TypeError: asciidoctorJs.Asciidoctor is not a function
    at Object.<anonymous> (C:\Code\...\node_modules\gulp-asciidoctor\index.js:6:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Code\...\build\tasks\asciidoc.js:3:16)
    at Module._compile (module.js:570:32)
```

**Comment by mojavelinux** [comment]
Seems to be the same as #269.

**Comment by Mogztter** [comment]
@lafe I've fixed this issue in https://github.com/asciidoctor/gulp-asciidoctor/pull/8

Let me know if this is working for you.

**Comment by Mogztter** [comment]
My fix is now merged and there's a new release of gulp-asciidoctor. @lafe could you please confirm that this is now working so we can close this issue ?

**Comment by lafe** [comment]
I will check next week as I currently do not have access to the installation where the issue occured.

**Comment by Mogztter** [comment]
@lafe Ok thanks :+1:

**Comment by lafe** [comment]
It works now. Thank you for implementing the fix!

**Comment by Mogztter** [comment]
You're welcome :smile:
