### ISSUE TITLE
Asciidoctor.js cross-compiled with Opal master (0.11) is invalid

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#279]
```
/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/asciidoctor.js:21733
        return ($a = transform, $b = self.converter_map, ((($c = $b['$[]']($a)) !== false && $c !== nil && $c != null) ? $c : $b['$[]=']($a, self.$find_converter(transform))))((($a = ) !== false && $a !== nil && $a != null) ? $a : self.converter_map['$[]'](transform, self.$find_converter(transform)))
                                                                                                                                                                                       ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/bower.spec.all.js:311:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by Mogztter** [comment]
Fixed in the latest integration branch: https://github.com/Mogztter/opal/commits/integration
