### ISSUE TITLE
Unable to have the sample.js working

### ISSUE THREAD

**Issue by rgoyardgop** [asciidoctor/asciidoctor.js#310]
Hi guys, 

  I'm currently trying to use this asciidoctor.js working for my project.
  I would like to make it work in a React project created in ES6 (transpilled using babel)
  I tried to make it work without any success, so I decided to try the code from README : 

`npm init -y`
`npm install -S asciidoctor.js`

Create the file _sample.js_ (from README file)

```js
var asciidoctor = require('asciidoctor.js')();
var content = "http://asciidoctor.org[*Asciidoctor*] " +
    "running on http://opalrb.org[_Opal_] " +
    "brings AsciiDoc to Node.js!";
var html = asciidoctor.convert(content);
console.log(html); 
```

And here is the output : 

```
⇒  node sample.js
/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/asciidoctor.js/dist/asciidoctor.js:35658
          } else { throw $err; }
                   ^

TypeError: Cannot read property 'join' of null
    at Date.$$zone [as $zone] (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/opal-runtime/src/opal.js:18510:62)
    at /Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/opal-runtime/src/opal.js:18691:28
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Date.$$strftime [as $strftime] (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/opal-runtime/src/opal.js:18554:21)
    at /Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/asciidoctor.js/dist/asciidoctor.js:25954:24
    at $Document.$$initialize [as $initialize] (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/asciidoctor.js/dist/asciidoctor.js:25961:14)
    at Object.Opal.send (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/opal-runtime/src/opal.js:1663:21)
    at singleton_class_alloc.TMP_Class_new_4 [as $new] (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/opal-runtime/src/opal.js:3441:12)
    at module_constructor.$$load [as $load] (/Users/remigoyard/Code/perso/babel-asccidoctor/node_modules/asciidoctor.js/dist/asciidoctor.js:35624:67)
```

Once I will i this working, i will try to make it work with babel ... 

I am running on a Mac OS  (10.12.4)

And node version is : v7.4.0

Does anyone has any ideas ? 

Thanks

Remi

**Comment by mojavelinux** [comment]
This appears to be #23 cropping back up again. Only this time, I don't understand how it's getting backs the catch block.

Please try the following directly in node:

```js
var asciidoctor = require('asciidoctor.js')();
console.log(Opal.Time.$now().$strftime('%H:%M:%S %Z'));
console.log(Opal.Time.$now().$strftime('%H:%M:%S %z'));
```

One of those is failing in your locale.

You can work around this problem by passing the localtime attribute to Asciidoctor.

```js
var html = asciidoctor.convert(content, { attributes: { 'localtime': '00:00:00' } });
```

**Comment by Mogztter** [comment]
@mojavelinux As mentioned by Ilya in https://github.com/opal/opal/issues/1675#issuecomment-308094240 we need to catch JavaScript's TypeError in Asciidoctor core ([document.rb#L426-L430](https://github.com/asciidoctor/asciidoctor/blob/b122f5f460bae2c567a4d9a219ff4b3d0810820b/lib/asciidoctor/document.rb#L426-L430))

**Comment by iliabylich** [comment]
@Mogztter Ideally it should be fixed in Opal. Methods from corelib shouldn't raise JS errors. `TIme.now.zone` is simply broken for some zone/browser combinations.

**Comment by Mogztter** [comment]
@iliabylich That's the best solution, thanks for digging into this issue 👍

**Comment by elia** [comment]
@Mogztter @iliabylich the bare minimum would be to catch JS TypeError and re-raise a Ruby error, we can definitely issue a 0.10 update with this "fix". Even better would be fixing the actual error (which I'm trying right now) 😄

**Comment by mojavelinux** [comment]
@Mogztter I'm getting very close to releasing Asciidoctor 1.5.6. Is there a change you want me to make in core or are you able to work upstream to solve it?

**Comment by Mogztter** [comment]
@mojavelinux As mentioned by Elia, this bug is fixed in Opal (and contained in this upgrade: https://github.com/asciidoctor/asciidoctor.js/pull/346). So there's nothing to do in Asciidoctor core :wink:

**Comment by mojavelinux** [comment]
Fantastic! I just wanted to be absolutely certain.

**Comment by Mogztter** [comment]
@rgoyardgop Could you please confirm that this bug is gone with the latest release https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.6-preview.3 ? Thanks.

**Comment by Mogztter** [comment]
@rgoyardgop ping ?

**Comment by Mogztter** [comment]
@rgoyardgop I'm closing this issue because I strongly believe it's fixed. If this is not the case feel free to reopen 😉

**Comment by kikijiki** [comment]
I'm using v1.5.7-beta.1 and have the same problem.
The string inside the zone function in my case is: `Tue May 29 2018 18:45:07 GMT+0900 (東京 (標準時))`

```
C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:33252
          } else { throw $err; }
                   ^

TypeError: Cannot read property 'join' of null
    at Date.ːzone [as $zone] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:17860:62)
    at C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:18048:28
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at Date.ːstrftime [as $strftime] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:17911:21)
    at $Document.ːinitialize [as $initialize] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:27367:58)
    at singleton_class_alloc.TMP_4 [as $new] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:3139:23)
    at module_constructor.ːload [as $load] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:33226:43)
    at module_constructor.ːconvert (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:33306:20)
    at module_constructor.Opal.Asciidoctor.$$class.$$proto.convert (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:33455:21)
```

By the way, I tried adding `return "JST";` as a workaround, but if I do so I get another unrelated error.
Looks like the path of an included image is wrong (I set `:imagesdir: img` and include it as `image::test.png[]`)

```
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'X:/test/X:/test/img/test.png'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at singleton_class_alloc.ːbinread [as $binread] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:23805:28)
    at $Block.ːgenerate_data_uri [as $generate_data_uri] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:26074:36)
    at $Block.ːimage_uri [as $image_uri] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:26039:25)
    at $Html5Converter.ːimage [as $image] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:21625:96)
    at $Html5Converter.ː__send__ (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:3227:21)
    at $Html5Converter.ːconvert [as $convert] (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:20544:24)
    at $Block.ːconvert (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:26341:34)
    at TMP_6 (C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js:26351:18)
```

Also I have no problems on the ruby version of Asciidoctor.

**Comment by kikijiki** [comment]
Ops, it's a closed issue. Pinging @Mogztter just to be sure it gets seen.

**Comment by kikijiki** [comment]
p.s.
I use the cli, don't know if makes a difference.

**Comment by Mogztter** [comment]
@kikijiki Are you sure that you are using the latest version because `Date.ːstrftime [as $strftime]` should be at line 20380: https://github.com/Mogztter/opal-node-runtime/blob/v1.0.5/src/opal.js#L20380
not 17911

```
C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\opal-runtime\src\opal.js:17911:21
```

Could you please open `C:\Users\user\AppData\Roaming\npm\node_modules\asciidoctor-cli\node_modules\asciidoctor.js\dist\asciidoctor.js` and look at the end of the file. You should see the `ASCIIDOCTOR_JS_VERSION`.

**Comment by Mogztter** [comment]
No worries! Actually you did nothing wrong :sweat_smile: 

The latest release of `asciidoctor-cli` is using Asciidoctor.js 1.5.5-4: https://github.com/asciidoctor/asciidoctor-cli.js/blob/v1.5.5-beta.3/package.json

I've just published a new version of `asciidoctor-cli@1.5.6-rc.1`. This version is not bound anymore to a specific version of Asciidoctor.js.

What you need to do is: `npm i -g asciidoctor.js asciidoctor-cli@1.5.6-rc.1`

This command should install the latest version of both `asciidoctor.js` and `asciidoctor-cli` (globally):

```
asciidoctorjs --version
1.5.6-rc.1
```

Let me know if it's working for you :wink:

**Comment by kikijiki** [comment]
Thank you very much, everything working fine now!

**Comment by Mogztter** [comment]
Awesome 👍
