### ISSUE TITLE
Implement File.write method in opal_ext

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#330]
Implement the static write method on File. Create an alias of this method on IO as well.

The write method provides a shorthand for the following.

```ruby
File.open('target', 'w') {|f| f.write content }
```

I'd like to consolidate these calls in core to:

```ruby
File.write 'target', content
```

**Comment by Mogztter** [comment]
Upstream issue (Opal): https://github.com/opal/opal/issues/1663

**Comment by Mogztter** [comment]
Here's the reason why you suggest to implement `File.write` ?

```
Failures:
1) webpack Parsing should return an empty string when there's no candidate for inline conversion
  Message:
    TypeError: Cannot read property 'write' of undefined
  Stack:
    TypeError: Cannot read property 'write' of undefined
        at $IO.write_proc (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:57428:72)
        at $IO.$$write [as $write] (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:57324:13)
        at $IO.$$puts [as $puts] (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:57377:17)
        at Opal.send (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:39665:24)
        at $Document.$$warn [as $warn] (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:42871:17)
        at $Document.$$convert [as $convert] (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:27182:21)
        at module_constructor.$$convert [as $convert] (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:36427:23)
        at module_constructor.Asciidoctor.$$proto.convert (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:36611:22)
        at Object.<anonymous> (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/build/webpack.spec.js:325:33)
```

**Comment by Mogztter** [comment]
In a Webpack environment `process` is defined but it's a different object:

```js
process { nextTick: [Function],
  title: 'browser',
  browser: true,
  env: {},
  argv: [],
  version: '',
  versions: {},
  on: [Function: noop],
  addListener: [Function: noop],
  once: [Function: noop],
  off: [Function: noop],
  removeListener: [Function: noop],
  removeAllListeners: [Function: noop],
  emit: [Function: noop],
  binding: [Function],
  cwd: [Function],
  chdir: [Function],
  umask: [Function] }
```

So Opal should check that `process` is an object and that `process.stderr` / `processo.stdout` are defined: https://github.com/opal/opal/blob/aabc78a24ab911493e99c87ac23b379a2b86e197/opal/corelib/io.rb#L73-L74

**Comment by Mogztter** [comment]
This should fix this issue: https://github.com/opal/opal/pull/1664

**Comment by mojavelinux** [comment]
> Here's the reason why you suggest to implement File.write ?

I think that's different. I'm not using IO.write or File.write yet, but I would like to in order to simplify the code (and speed it up a fraction).

**Comment by Mogztter** [comment]
Resolved in https://github.com/opal/opal/pull/1672 and integrated in Asciidoctor.js in https://github.com/asciidoctor/asciidoctor.js/commit/c28dfa60de30bf43f4413bd208918fc976b6bdfd

**Comment by mojavelinux** [comment]
:+1:
