### ISSUE TITLE
Providing metadata to convert method, extracting metadata from document

### ISSUE THREAD

**Issue by robogeek** [asciidoctor/asciidoctor.js#365]
I'm mapping out how to approach adding AsciiDoctor support to AkashaCMS.  I finally read the documentation and this is a very interesting system.  

What AsciiDoc calls "attributes" I would call Metadata.  Anyway, AkashaCMS has its own metadata for each document that's declared in a YAML frontmatter block.  I think there are two things required to integrate AkashaCMS metadata with AsciiDoctor attributes.

1. When the `convert` method is called, it needs to somehow receive the document metadata AkashaCMS collected, making that data available as attributes inside the doucment
1. Export the attributes in the document into AkashaCMS document metadata

Do those make sense?

Unfortunately the only method documented in AsciiDoctor.js is the `convert` method.  And it only receives the text to convert.

I see http://asciidoctor.org/docs/user-manual/#api and a few interesting-looking **Ruby** methods.  Are those available from AsciDoctor.js as well?

And, as long as I'm here, there are two other questions

1. Can I set the directory for include files?
1. The `template_dir` option works to set a template directory?

**Comment by Mogztter** [comment]
> I see http://asciidoctor.org/docs/user-manual/#api and a few interesting-looking Ruby methods. Are those available from AsciDoctor.js as well?

Yes!
You can use the following to pass attributes:

```js
var options = { attributes: { icons: 'font', sectnums: true } };
var doc = asciidoctor.load('= Test', options);
```

On the Document object you can fetch attributes/metadata:

```js
var author = doc.getAttributes()['author'];
```
Here's the complete list: http://asciidoctor.github.io/asciidoctor.js/master/#document

> Can I set the directory for include files?

You mean `base_dir` ? http://asciidoctor.org/docs/user-manual/#ruby-api-options
```js
var options = { base_dir: '/path/to/base/dir' };
var doc = asciidoctor.load('= Test', options);
```

> The template_dir option works to set a template directory?

Template backend in Asciidoctor.js is a bit tricky. Could you give me some context ?
If you want to use Jade templates, you will need to use https://github.com/asciidoctor/asciidoctor-template.js

**Comment by Mogztter** [comment]
@robogeek How the integration is going ?
Just so you know, I've updated the [user manual](https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc). Please tell me, if you have more questions.

**Comment by robogeek** [comment]
I've been awfully busy with some other projects however I had given the above a go and came up with a problem.

My rendering function:

```
convert(text, metadata) {
        var options = metadata.asciidoctor ? metadata.asciidoctor : {
            doctype: this[_renderer_doctype]
        };
        options.attributes = metadata;
        // console.log(`convert ${util.inspect(options)}`);
        return asciidoctor.convert(text, options);
    }
```

The `metadata` parameter is created by AkashaRender from several sources.  It is a highly nested object that contains functions in addition to fields holding String values.

This is similar to the code you added to your user manual in the **how to use conversion options** section.  Unfortunately, when I run this on my test website I get the following error.  If I comment out the line assigning to `options.attributes` then the following error goes away, and the AsciiDoc page is rendered correctly except the values deriving from the AkashaRender metadata of course do not get rendered into the document.

```
Error rendering asciidoctor.html.adoc TypeError: val.$nil? is not a function
    at TMP_10 (/Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:27034:35)
    at $Hash.$$delete_if [as $delete_if] (/Users/david/akasharender/akashacms-example/node_modules/opal-runtime/src/opal.js:14071:15)
    at Opal.send (/Users/david/akasharender/akashacms-example/node_modules/opal-runtime/src/opal.js:1609:19)
    at $Document.$$initialize [as $initialize] (/Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:27030:9)
    at Object.Opal.send (/Users/david/akasharender/akashacms-example/node_modules/opal-runtime/src/opal.js:1609:19)
    at singleton_class_alloc.TMP_Class_new_5 [as $new] (/Users/david/akasharender/akashacms-example/node_modules/opal-runtime/src/opal.js:3461:12)
    at /Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:37405:66
    at module_constructor.$$load [as $load] (/Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:37406:28)
    at module_constructor.$$convert [as $convert] (/Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:37523:20)
    at module_constructor.Asciidoctor.$$proto.convert (/Users/david/akasharender/akashacms-example/node_modules/asciidoctor.js/dist/asciidoctor.js:37758:21)
    at AsciidocRenderer.convert (/Users/david/akasharender/akashacms-example/node_modules/akasharender/render-asciidoc.js:40:28)
    at e (/Users/david/akasharender/akashacms-example/node_modules/akasharender/render-asciidoc.js:54:30)
    at AsciidocRenderer.render (/Users/david/akasharender/akashacms-example/node_modules/akasharender/render-asciidoc.js:52:16)
    at /Users/david/akasharender/akashacms-example/node_modules/akasharender/HTMLRenderer.js:133:50
    at next (native)
    at onFulfilled (/Users/david/akasharender/akashacms-example/node_modules/co/index.js:65:19)
```

You can replicate this by cloning the akashacms-example site from https://github.com/akashacms/akashacms-example then:

```
$ cd akashacms-example
$ npm init
$ npm run build
```

By default it does not set `options.attribute` and will render the site without error, but without substituting the attributes.  Next, edit `node_modules/akasharender/render-asciidoc.js` and uncomment out the `options.attribute` line, then rerun the last command.

**Comment by Mogztter** [comment]
> The metadata parameter is created by AkashaRender from several sources. It is a highly nested object that contains functions in addition to fields holding String values.

You cannot pass an object that contains functions to `options.attributes`.
The attribute value should be a boolean, a String or a number.

> All attributes have a name and a value (though the value may be implicit).
> The attribute name:
> * must be at least one character long,
> * must begin with a word character (A-Z, a-z, 0-9 or _) and
> * must only contain word characters and hyphens.

http://asciidoctor.org/docs/user-manual/#attribute-restrictions

**Comment by robogeek** [comment]
Okay, thank you, that's what I thought might be the problem.  I'll have to ponder this issue because for other parts of the system the functions are required.

Maybe a simple function in that Renderer to sanitize the attributes object .... copy over every attribute that's a boolean/string/number and leave the others behind.

**Comment by Mogztter** [comment]
> Maybe a simple function in that Renderer to sanitize the attributes object .... copy over every attribute that's a boolean/string/number and leave the others behind.

Yes that's a good idea, you cannot use them in Asciidoctor anyway 😐
