### ISSUE TITLE
Cannot convert to docbook

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#479]
Hello,

I'm trying to convert an Asciidoc file to Docbook. It seems to fail because it cannot find `asciidoctor/converter/docbook5`:

```
/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:16537
          } else { throw $err; }
                   ^
LoadError: cannot load such file -- asciidoctor/converter/docbook5
    at Object.Opal.load (/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:2210:32)
    at $Factory.Opal.require [as $require] (/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:2230:17)
    at /Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:5114:18
    at $Factory.$$create [as $create] (/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:5129:32)
    at $Document.$$create_converter [as $create_converter] (/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:6692:34)
    at $Document.$$update_backend_attributes [as $update_backend_attributes] (/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:6522:142)
    at $Document.$$initialize [as $initialize] (/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:5866:16)
    at Object.Opal.send (/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:1610:19)
    at singleton_class_alloc.TMP_Class_new_5 [as $new] (/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:3490:12)
    at /Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/node/asciidoctor.js:16503:66
```

The conversion works fine when I switch the backend back to `html5`.

**Comment by Mogztter** [comment]
Hello Thomas,

Are you using https://github.com/mogztter/asciidoctor-docbook.js ?
We've decided to move the docbook backend to a separated module (though I should make it clear somewhere in the documentation).

Let me know if it's working 😉

**Comment by oncletom** [comment]
Ah no! I was using only this one.

I follow the instructions in mogztter/asciidoctor-docbook.js and it's all good now :-)

Thanks a lot!

PS: next stage is to try the LibreOffice DocBook to ODT converter…
