### ISSUE TITLE
ReferenceError: Opal is not defined

### ISSUE THREAD

**Issue by GoGoris** [asciidoctor/asciidoctor.js#507]
Since this week I am getting an error when I try to use the plugin.
This could be related to npm 6 which I installed today.

Stacktrace (Visual Studio Code development tools):
```
ReferenceError: Opal is not defined
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\opal.js:2316:1)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\opal.js:22183:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\index.js:2:1)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\index.js:13:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\asciidoctor.js\dist\node\asciidoctor.js:2:14)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\asciidoctor.js\dist\node\asciidoctor.js:18510:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\text-parser.js:13:21)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\text-parser.js:127:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\TextDocumentContentProvider.js:12:21)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\TextDocumentContentProvider.js:95:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\extension.js:15:39)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\extension.js:84:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:131
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:243)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:720:161)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:48)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:428:188)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:757
	at Array.map (native)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:732)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:426:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:412)
	at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:722:827)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

### Version information
Npm: 6.0.1
Node: 8.11.1
Visual Studio Code: 1.23.1

**Comment by Mogztter** [comment]
Hello @GoGoris 

Thanks for your report. I'm not familiar with the VS Code extension, could you please open an issue over there: https://github.com/joaompinto/asciidoctor-vscode ? I believe that @joaompinto will be able to help you.

**Comment by Mogztter** [comment]
The Asciidoctor VS code extension is not using a strict version so maybe the latest release of Asciidoctor.js is not compatible with the extension.
I will reproduce this issue tomorrow by installing VS code and the extension.

**Comment by GoGoris** [comment]
Hmm, I found that the error is gone when I uninstall the "Bracket Colorizer" extension. 
It is weird how extensions can break eachother in Vs code. Issue: joaompinto/asciidoctor-vscode#88

The problem must be in the extension so I am closing this issue.
