### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by darlenya** [asciidoctor/asciidoctor.js#563]
Hi, when I use the MemoryLogger I get the Error:

TypeError: Cannot read property 'length' of undefined
    at fromHash (/Users/torstenlink/Documents/entwicklung/bahn/e2e/e2e-doc/adoc-demo/node_modules/asciidoctor.js/dist/node/asciidoctor.js:18163:70)
    at $MemoryLogger.MemoryLogger.getMessages (/Users/torstenlink/Documents/entwicklung/bahn/e2e/e2e-doc/adoc-demo/node_modules/asciidoctor.js/dist/node/asciidoctor.js:19530:31)

This is caused by an error by using 
:source-highlighter: coderay

index.js

```javascript
const asciidoctor = require('asciidoctor.js')();

const memoryLogger = asciidoctor.MemoryLogger.$new()
asciidoctor.LoggerManager.setLogger(memoryLogger)

const doc = asciidoctor.loadFile('./main.adoc', {
	safe: 'unsafe',
	catalog_assets: true,
	backend: 'xhtml',
})

const html = doc.convert()
const errorMessages = memoryLogger.getMessages()
console.log(errorMessages)
```

main.adoc

```
:source-highlighter: coderay
[source, bash]
----
ls -la
----
```

**Comment by Mogztter** [comment]
Thanks for your report @danhyun.
It's most likely a bug in Asciidoctor.js. The code assumes that a message should always contain an Hash named `message` but this assumption seems to be wrong.

I will add a test with our sample to reproduce and fix this issue before the next release.
Sorry about that 😞
