### ISSUE TITLE
input_mtime.$strftime is not a function when testing with jest

### ISSUE THREAD

**Issue by darlenya** [asciidoctor/asciidoctor.js#565]
Hi, I am not sure if this is bug is located to asciidoctor or jest or opal.

But when I test my code I get the following error:

```javascript
  TypeError: input_mtime.$strftime is not a function

       6 | 	asciidoctor.LoggerManager.setLogger(memoryLogger)
       7 | 
    >  8 | 	const doc = asciidoctor.loadFile('./main.adoc', {
         | 	                        ^
       9 | 		safe: 'unsafe',
      10 | 		catalog_assets: true,
      11 | 		backend: 'xhtml',

      at Function.$$load (node_modules/asciidoctor.js/dist/node/asciidoctor.js:17833:61)
      at TMP_11 (node_modules/asciidoctor.js/dist/node/asciidoctor.js:17923:21)
      at Object.<anonymous>.Opal.yield1 (node_modules/opal-runtime/src/opal.js:1429:14)
      at node_modules/opal-runtime/src/nodejs.js:247:21
 
```

Here is my code:

index.js 
```javascript
const asciidoctor = require('asciidoctor.js')();
exports.convert = function (){
	const doc = asciidoctor.loadFile('./main.adoc', {
		safe: 'unsafe',
		catalog_assets: true,
		backend: 'xhtml',
	})
	const html = doc.convert()
	return html
}
```

index.test.js 
```javascript
const convert = require('./index').convert
test('Convert Dokument', async done => {
	const res = convert()
	expect(res).toEqual('')
})
```

main.adoc
```
== Some Text
[source, bash]
----
ls -la
----
```

package.json
index.js 
```json
{
  "name": "adoc-demo",
  "version": "1.0.0",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "asciidoctor.js": "^1.5.7-rc.1"
  },
  "devDependencies": {
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0"
  }
}
```

**Comment by Mogztter** [comment]
Hello @darlenya, could you please confirm that you only reproduce this issue in a Jest test ? We do have plenty of tests in this repository on the `loadFile` function.

It's most likely a bad interaction between Opal + Asciidoctor and Jest... :thinking:

**Comment by darlenya** [comment]
Hi, I have made a test with 'mocha' which is working. So I  need to switch to mocha.

**Comment by Mogztter** [comment]
Yes as a workaround you can switch to Mocha or Jasmine. Both are working fine with Asciidoctor.js.
Still Asciidoctor.js should work with Jest. I will investigate 👀

**Comment by Mogztter** [comment]
I can reproduce this issue!

The problem is that (somehow) the method `File#mtime` returns a JavaScript `Date` object instead of a Ruby `Time` object.

In a Node.js environment, we are using the following code to get the last time this file was modified:

```js
fs.statSync(path).mtime
```

Normally Opal will "lift" the JavaScript `Date` object to a Ruby `Time` object. I don't remember how Opal do it but this is what we expect.
With Jest since the returned object is just a JavaScript `Date`, the Ruby method `strftime` is not defined/available and we get `TypeError: input_mtime.$strftime is not a function`.

Now I'm trying to find out why it's not working in a Jest environment...

**Comment by Mogztter** [comment]
I believe that Jest has an isolation mechanism. I don't know exactly how but when `new Date()` is called in the `fs` core module, the `Date` object is not lifted to a Ruby `Time` object...

Unfortunately I didn't find a way to workaround this isolation (and in theory it's a good thing to isolate context):

```js
test('Date lifted', function() {
  const date1 = new Date();

  // load Opal
  require('opal-runtime')
  Opal.load("nodejs")

  const date2 = require('fs').statSync('./main.adoc').mtime
  const date3 = new Date()

  expect(typeof date1.$strftime).toEqual('function')   // date1 is lifted
  expect(typeof date2.$strftime).toEqual('undefined')  // date2 is not lifted :(
  expect(typeof date3.$strftime).toEqual('function')   // date3 is lifted
})
```

**Comment by Mogztter** [comment]
That makes sense. Thanks for the workaround Martijn.

I don't think there much we can do about it in Asciidoctor.js. It's more an issue with how Opal is working and how Jest environment are initialized.

I think we should document how to workaround this issue in the documentation and close this issue. Do you agree ?

**Comment by martijnthe** [comment]
Sounds good to me. Feel free to take the code I posted and document it elsewhere.

Perhaps open an issue in Opal’s issue tracker? I doubt this is unique to asciidoctor.js

**Comment by Mogztter** [comment]
As expected there's nothing much we can do at Opal level (this is really an integration/environment issue).

I will take your code and document it in the user manual.

Thanks again @darlenya for raising this issue and @martijnthe for the workaround :smile:

**Comment by darlenya** [comment]
Hi , I am very happy with this workaround. Thanks @martijnthe

**Comment by ggrossetie** [comment]
No longer relevant, the next version of Asciidoctor.js no longer uses Opal.
