### ISSUE TITLE
LoadError when using template_dirs option

### ISSUE THREAD

**Issue by elmiko** [asciidoctor/asciidoctor.js#735]
i am attempting to follow the guidance for using a template with my asciidoctor conversions and have run into an unexpected error.

my setup is a node.js application that uses the following code snippet to process the documents:

```
var adoc = asciidoctor.convertFile(filename, {to_dir: destination, template_dirs: ["/full/path/to/template/dir"]});
```

in my template dir, i have copied the upstream `document.html.erb` file [from here](https://github.com/asciidoctor/asciidoctor-backends/blob/master/erb/html5/document.html.erb).

when i run my application i see the following error message:

```
/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:19584
          } else { throw $err; }
                   ^
LoadError: cannot load such file -- asciidoctor/converter/template
    at Object.Opal.load (/home/mike/workspace/stasis-reactor/node_modules/opal-runtime/src/opal.js:2308:32)
    at $Factory.Opal.require (/home/mike/workspace/stasis-reactor/node_modules/opal-runtime/src/opal.js:2328:17)
    at $Factory.$$create (/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:6458:18)
    at $Document.$$create_converter (/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:8184:34)
    at $Document.$$update_backend_attributes (/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:8019:10
0)
    at $Document.$$initialize (/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:7278:16)
    at Object.Opal.send (/home/mike/workspace/stasis-reactor/node_modules/opal-runtime/src/opal.js:1660:19)
    at Function.TMP_Class_new_5 (/home/mike/workspace/stasis-reactor/node_modules/opal-runtime/src/opal.js:3608:12)
    at /home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:19550:45
    at Function.$$load (/home/mike/workspace/stasis-reactor/node_modules/asciidoctor.js/dist/node/asciidoctor.js:19551:28)
```

i had thought that `erb` files were a default template option, do i need to enable a specific backend to make this work?

should i be using a different template format, and if so where can i find an example?

it is unclear to me from the documentation on asciidoctor.js what i should be doing to make this linkage happen, any guidance is appreciated.

**Comment by Mogztter** [comment]
Hello @elmiko 

ERB is a templating system for Ruby: https://ruby-doc.org/stdlib-2.6.3/libdoc/erb/rdoc/ERB.html

In Asciidoctor.js we do not have a built-in template converter but it's relatively easy to create a custom HTML5 converter: https://blog.yuzutech.fr/blog/1.0/custom-converter/index.html

```js
const asciidoctor = require('asciidoctor.js')()

class TemplateConverter {
  constructor () {
    this.baseConverter = asciidoctor.Html5Converter.$new() 
    this.templates = {
      paragraph: (node) => `<p class="paragraph">${node.getContent()}</p>` 
    }
  }

  convert (node, transform, opts) {
    const template = this.templates[transform || node.node_name]
    if (template) { 
      return template(node) 
    }
    return this.baseConverter.convert(node, transform, opts) 
  }
}
asciidoctor.ConverterFactory.register(new TemplateConverter(), ['html5']) 

// convert your document...
```

If you want, you could extend this example and use a JavaScript template engine like [Pug](https://pugjs.org/api/getting-started.html) (instead of using [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)).

We do not have a built-in template converter because we don't want to introduce a dependency on a specific template engine.
You can also try: https://github.com/s-leroux/asciidoctor.js-template

**Comment by elmiko** [comment]
@Mogztter thank you very much!

i had thought i might be running into something like this, i did see s-leroux's work but i didn't quite understand it. thank you again for the concise example, i will experiment with this.

i'm going to close this issue.
