### ISSUE TITLE
Error calling hasSection()

### ISSUE THREAD

**Issue by henriette-einstein** [asciidoctor/asciidoctor.js#850]
I try to implement a custom converter that uses handlebars for generating the converter output. I therefore use generic functions to generate properties for Hanldebars. Whenever I encounter an AbstractBlock, I call all methods of that class.

As far as I can see, a paragraph node is an abstract block. However, If I call the method **hasSections()** in that case, I get an exception

```
>: undefined method `>' for nil
```

Here a testfile to reproduce the error:

```js
const Asciidoctor = require("asciidoctor")();

class TestConverter {
  constructor(baseConverter) {
    this.baseConverter = baseConverter;
  }

  convert(node, transform) {
    const nodeName = transform || node.getNodeName();
    if (nodeName === "paragraph") {
      const ret =
        '<div class="' +
        (node.hasBlocks() ? "with-blocks" : "no-blocks") +
        " " +
        (node.hasSections() ? "with-sections" : "no-sections") +
        '">' +
        "<p>" +
        node.getContent() +
        "</p>" +
        "</div>";
      return ret;
    }
    return this.baseConverter.convert(node, transform);
  }
}

const myConverter = new TestConverter(Asciidoctor.Html5Converter.create());
Asciidoctor.ConverterFactory.register(myConverter, ["html5"]);
console.log(Asciidoctor.convert("This is a test"));```
````

When I run this file, I get the following stack-trace

```
/Users/arpablo/testAsciiDoctorJS/node_modules/asciidoctor-opal-runtime/src/opal.js:4665
      throw exception;
      ^
>: undefined method `>' for nil
    at constructor.$method_missing (/Users/arpablo/testAsciiDoctorJS/node_modules/asciidoctor-opal-runtime/src/opal.js:3907:56)
    at constructor.method_missing_stub (/Users/arpablo/testAsciiDoctorJS/node_modules/asciidoctor-opal-runtime/src/opal.js:1310:35)
    at $rb_gt (/Users/arpablo/testAsciiDoctorJS/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:5298:90)
    at constructor.$sections? (/Users/arpablo/testAsciiDoctorJS/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:5437:16)
    at constructor.AbstractBlock.hasSections (/Users/arpablo/testAsciiDoctorJS/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21692:28)
    at TestConverter.convert (/Users/arpablo/testAsciiDoctorJS/index.js:14:18)
    at constructor.$convert (/Users/arpablo/testAsciiDoctorJS/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:5385:34)
    at $$8 (/Users/arpablo/testAsciiDoctorJS/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:5399:20)
    at Object.Opal.yield1 (/Users/arpablo/testAsciiDoctorJS/node_modules/asciidoctor-opal-runtime/src/opal.js:1452:14)
    at Array.$collect (/Users/arpablo/testAsciiDoctorJS/node_modules/asciidoctor-opal-runtime/src/opal.js:12124:26) {
  name: '>',
  message: "undefined method `>' for nil",
  args: [ 0 ]
}

```
When I comment out the line with `node.hasSection()...` everything works fine.
Any idea?

**Comment by Mogztter** [comment]
Hello @henriette-einstein

You are calling `sections?` on a Node which is not a Document or a Section. In this case, the implementation (in Ruby) does not assign a value to `@next_section_index`:


https://github.com/asciidoctor/asciidoctor/blob/88bc891d6a0143f3a2142f41d29cabe3cb21fe3f/lib/asciidoctor/abstract_block.rb#L41-L48

The value is `nil` and the method `sections?` (in Ruby) is doing:

```rb
def sections?
  @next_section_index > 0
end
```

https://github.com/asciidoctor/asciidoctor/blob/88bc891d6a0143f3a2142f41d29cabe3cb21fe3f/lib/asciidoctor/abstract_block.rb#L135-L137

So in your case, `nil > 0`:

```
$ ruby -e 'nil > 0'
-e:1:in `<main>': undefined method `>' for nil:NilClass (NoMethodError)
```

I'm not sure why this method is available on an AbstractNode. From the current implementation, it seems that this method should only be defined on a `Section` and `Document` node.

@mojavelinux Should we move this issue to Asciidoctor core? 

To workaround this issue, you should not call `hasSections` on a paragraph (because a paragraph does not have section, unless I'm missing something)

**Comment by mojavelinux** [comment]
Since this method is defined on AbstractBlock, it seems reasonable that it would return false for anything that isn't itself a section. So yes.
