### ISSUE TITLE
shell:rakeDist failed

### ISSUE THREAD

**Issue by aidanhs** [asciidoctor/asciidoctor.js#86]
```
$ grunt dist
[...]
Running "shell:rakeDist" (shell) task
Warning: Command failed: Cannot handle dynamic require :asciidoctor/helpers:20
Cannot handle dynamic require :asciidoctor/converter/factory:49
Cannot handle dynamic require :asciidoctor/converter/factory:197
Cannot handle dynamic require :asciidoctor/converter/factory:202
Cannot handle dynamic require :asciidoctor/converter/factory:207
Cannot handle dynamic require :asciidoctor/converter/factory:215
Cannot handle dynamic require :asciidoctor/converter/factory:218
rake aborted!
NoMethodError: undefined method `write_to' for nil:NilClass
/adb/asciidoctor.js/Rakefile:45:in `block (2 levels) in <top (required)>'
/adb/asciidoctor.js/Rakefile:45:in `each'
/adb/asciidoctor.js/Rakefile:45:in `block in <top (required)>'
Tasks: TOP => dist
(See full trace by running task with --trace)
 Use --force to continue.
```

With --trace added to Gruntfile.js:
```
Running "shell:rakeDist" (shell) task
Warning: Command failed: * Invoke dist (first_time)
* Execute dist
Cannot handle dynamic require :asciidoctor/helpers:20
Cannot handle dynamic require :asciidoctor/converter/factory:49
Cannot handle dynamic require :asciidoctor/converter/factory:197
Cannot handle dynamic require :asciidoctor/converter/factory:202
Cannot handle dynamic require :asciidoctor/converter/factory:207
Cannot handle dynamic require :asciidoctor/converter/factory:215
Cannot handle dynamic require :asciidoctor/converter/factory:218
rake aborted!
NoMethodError: undefined method `write_to' for nil:NilClass
/adb/asciidoctor.js/Rakefile:45:in `block (2 levels) in <top (required)>'
/adb/asciidoctor.js/Rakefile:45:in `each'
/adb/asciidoctor.js/Rakefile:45:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => dist
 Use --force to continue.

Aborted due to warnings.
```

i.e.
```
endorsed_extensions.each { |extension| env[extension].write_to "build/asciidoctor-#{extension}.js#{compress ? '.gz' : nil}" }
```

Was because I hadn't done `git submodule update --init --recursive`. Can you add this to the instructions?

**Comment by Mogztter** [comment]
Resolved by #106 and #71
