### ISSUE TITLE
A Logger test is "randomly" failing on the CI

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#885]
From time to time, the following error is thrown in the tests suite:

```
  1) Node.js
       Logger
         should use the built-in Logger:
     TypeError: Cannot read property '1' of null
      at Context.<anonymous> (spec\node\asciidoctor.spec.js:88:37)
      at processImmediate (internal/timers.js:456:21)
```

I have yet to reproduce this issue on my local workspace but we should try to understand the root cause...

It happened on Windows runner (GitHub Actions): https://github.com/asciidoctor/asciidoctor.js/pull/879/checks?check_run_id=526081937

**Comment by Mogztter** [comment]
It seems that macos runner on GitHub Actions is unstable. Tests are also randomly failing with timeout issues:

```
  1) Node.js
       Loading file
         should be able to retrieve structural content from file:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/runners/2.165.2/work/asciidoctor.js/asciidoctor.js/packages/core/spec/node/asciidoctor.spec.js)
``` 

We could increase the default timeout to 5 seconds to accommodate this runner but at the same time I don't want to hide things under the carpet...
